#!/bin/zsh

# aicommit function - Generate commit messages using Ollama
# Usage: aicommit [optional commit message prefix]

aicommit() {
    # Check if there are any staged changes
    if git diff --cached --quiet; then
        echo "No staged changes found. Please run 'git add' first."
        return 1
    fi

    # Get the diff of staged changes
    local staged_diff=$(git diff --cached)
    
    if [ -z "$staged_diff" ]; then
        echo "No staged changes to commit."
        return 1
    fi

    # Get model from environment variable or fetch from Ollama
    local model="${OLLAMA_MODEL:-}"
    
    if [ -z "$model" ]; then
        echo "No OLLAMA_MODEL set, fetching available models..."
        
        # Check if Ollama is running
        if ! curl -s http://localhost:11434/api/tags > /dev/null 2>&1; then
            echo "Error: Ollama is not running or not accessible at http://localhost:11434"
            echo "Please start Ollama or check your connection."
            return 1
        fi
        
        # Fetch available models
        local models_json=$(curl -s http://localhost:11434/api/tags)
        
        if [ -z "$models_json" ] || [ "$models_json" = "null" ]; then
            echo "Error: Failed to fetch models from Ollama."
            return 1
        fi
        
        # Extract first model name using jq if available, otherwise use grep/sed
        if command -v jq > /dev/null 2>&1; then
            model=$(echo "$models_json" | jq -r '.models[0].name // empty' 2>/dev/null)
        else
            # Fallback: extract first model name using grep/sed
            model=$(echo "$models_json" | grep -o '"name":"[^"]*"' | head -1 | sed 's/"name":"\([^"]*\)"/\1/')
        fi
        
        if [ -z "$model" ] || [ "$model" = "null" ]; then
            echo "Error: No models found in Ollama. Please install a model first."
            echo "Example: ollama pull llama2"
            return 1
        fi
        
        echo "Using model: $model"
    else
        echo "Using model from OLLAMA_MODEL: $model"
    fi

    # Prepare the prompt for Ollama
    # Use ollama_prompt instead of prompt to avoid conflict with zsh's built-in prompt variable
    local ollama_prompt="Generate a concise git commit message based on the following diff. 
The commit message should follow conventional commit format if applicable.
IMPORTANT: Return ONLY the commit message text, no markdown formatting, no code blocks, no backticks, no explanations.
Just the plain commit message text.

\`\`\`diff
${staged_diff}
\`\`\`"

    # Call Ollama CLI to generate commit message (much faster than curl)
    echo "Generating commit message..."
    
    # Check if ollama command is available
    if ! command -v ollama > /dev/null 2>&1; then
        echo "Error: ollama command not found. Please install Ollama CLI."
        echo "Visit: https://ollama.ai"
        return 1
    fi
    
    # Use ollama run command - much simpler and faster
    local commit_msg=""
    
    commit_msg=$(echo "$ollama_prompt" | ollama run "$model" --hidethinking 2>&1)
    
    local ollama_exit_code=$?
    
    # Check for errors
    if [ $ollama_exit_code -ne 0 ]; then
        if [ -z "$commit_msg" ]; then
            echo "Error: Failed to generate commit message from Ollama."
            echo "Exit code: $ollama_exit_code"
            return 1
        fi
        # If we have partial response, continue
    fi
    
    if [ -z "$commit_msg" ]; then
        echo "Error: No response from Ollama."
        return 1
    fi
    
    # Clean ANSI escape codes from ollama output (spinner, colors, etc.)
    commit_msg=$(echo "$commit_msg" | sed 's/\x1b\[[0-9;]*m//g' | sed 's/\x1b\[[0-9;]*[a-zA-Z]//g' | sed 's/\x1b\[?[0-9;]*[hl]//g')
    
    # Check if we got a valid response
    if [ -z "$commit_msg" ]; then
        echo "Error: No response from Ollama."
        return 1
    fi
    
    # If message is empty or only contains whitespace/markdown, show error
    # Use proper quoting to prevent shell interpretation of special characters
    if [ -z "${commit_msg}" ] || [ "${commit_msg}" = "```" ] || [ "${commit_msg}" = "`" ]; then
        echo "Error: Generated commit message is empty or invalid."
        echo "The model may not have generated a proper response."
        return 1
    fi
    
    # If user provided a prefix, prepend it
    if [ -n "${1:-}" ]; then
        commit_msg="${1}: ${commit_msg}"
    fi
    
    
    echo ""
    echo "Suggested commit message:"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "$commit_msg"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    
    # Record Which AI Model is used for commit msg
    model_info="[Generated by ${model}]"
    commit_msg="${commit_msg}\n\n${model_info}"
    
    # Ask user if they want to commit
    read "?Do you want to commit with this message? (y/N): " confirm
    if [[ "$confirm" =~ ^[Yy]$ ]]; then
        git commit -m "$commit_msg"
        echo "Committed successfully!"
    else
        echo "Commit cancelled."
    fi
}

